image:
  tag: ""

serviceAccount:
  name: notification-service-sa

vault:
  role: "pizzashop-staging"
  secretPath: "kv/pizzashop/staging/notification"

# Миграции для staging
migrations:
  enabled: true
  type: "up"
  image:
    tag: ""
  vault:
    role: "pizzashop-staging"
    secretPath: "kv/pizzashop/staging/migrations"
  databaseName: "notification_staging_db"
  dbHost: "nginx-egress.egress-gateway.svc.cluster.local"
  dbPort: "9001"

configMap:
  LOG_LEVEL: "info"
  RABBITMQ_HOST: "rabbitmq.pizzashop-staging.svc.cluster.local"
  RABBITMQ_PORT: "5672"